Add case insensitive name sorting support
aperezdc/ngx-fancyindex pull request #124
Opened 2021-01-22 23:58 UTC by mlniang

Add the fancyindex_case_sensitive option which considers the case when sorting by name if it is "on" (default option to keep current behavior) and does a case insensitive name sorting if it is "off". Tested on Ubuntu 20.04.1 LTS with Nginx 1.19.6

2022-05-10 18:48 UTC, ryandesign reviewed
Thank you! I love it. It works for me with nginx 1.21.6 on macOS 10.15.7. I recommend this PR be accepted after making the stylistic corrections mentioned in my comments below.

Looks like this will fix #78. Could you add the line `Closes #78` to the commit message?

It would be good to add a test for this feature to the test suite. The owner of this repository may want you to write that test in this PR, so that the automated checks can verify that it passes, or maybe they will allow the test to be written later.

2022-05-10 18:48 UTC, ryandesign commented on ngx_http_fancyindex_module.c
> +    }
The rest of this file always uses a space after an `if` statement so I suggest doing that here too:

```suggestion
    if (case_sensitive) {
        return (int) ngx_strcmp(second->name.data, first->name.data);
    } else {
        return (int) ngx_strcasecmp(second->name.data, first->name.data);
    }
```

Some `if` and `else` statements in this file that are only followed by one statement omit the curly braces; if that is the desired style of this file, I suggest:

```suggestion
    if (case_sensitive)
        return (int) ngx_strcmp(second->name.data, first->name.data);
    else
        return (int) ngx_strcasecmp(second->name.data, first->name.data);
```

Personally I find it clearer when curly braces are always used but the owner of this repository can say which style they prefer.

2022-05-10 18:48 UTC, ryandesign commented on ngx_http_fancyindex_module.c
> +    }
Same here: either:

```suggestion
    if (case_sensitive) {
        return (int) ngx_strcmp(first->name.data, second->name.data);
    } else {
        return (int) ngx_strcasecmp(first->name.data, second->name.data);
    }
```

or:

```suggestion
    if (case_sensitive)
        return (int) ngx_strcmp(first->name.data, second->name.data);
    else
        return (int) ngx_strcasecmp(first->name.data, second->name.data);
```

2022-05-10 19:37 UTC, ryandesign commented
Forgot to mention: could you hard wrap the commit message at 72 characters?

https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

2022-05-25 21:26 UTC, aperezdc commented on ngx_http_fancyindex_module.c
> +    }
I also have a tendency to prefer always using curly braces, to avoid ambiguity.

2022-05-25 21:33 UTC, aperezdc requested changes
@mlniang Could you take a look at the comment I added below? I think that @ryandesign also has made some good points.

2022-05-25 21:33 UTC, aperezdc commented on ngx_http_fancyindex_module.c
> +ngx_flag_t case_sensitive = 1;
Please don't use a global here. If different worker threads are handling requests simultaneously for e.g. locations where the setting is different, one of them will easily get the wrong value. 

Instead, you will want to define functions `ngx_http_fancyindex_cmp_entries_name_case_desc()` and `ngx_http_fancyindex_cmp_entries_name_case_asc()`, and pick the correct one below next to the comment that reads `/* Pick the sorting criteria. */` (around line 925).

2022-06-03 21:40 UTC, ryandesign commented
Since it's been so long since @mlniang submitted this and may no longer be working on it, I'll see if I can finish it up. I wrote a couple simple tests for it, and I'll see if I can figure out how to fix what you pointed out about avoiding the global flag.

2023-01-20 13:26 UTC, closed without merging